AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  A deno runtime for AWS Lambda

Resources:
  DenoLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: deno
      Description: deno-lambda DENO_LAMBDA_VERSION
      Content:
        S3Bucket: DENO_LAMBDA_BUCKET
        S3Key: deno-lambda-layer_DENO_LAMBDA_VERSION.zip

Outputs:
  LayerArn:
    Value: !Ref DenoLambdaLayer

Metadata:
  AWS::ServerlessRepo::Application:
    Name: deno
    Description: |
      A deno runtime for AWS Lambda
    Author: Andy Hayden
    SpdxLicenseId: MIT
    Labels:
    - deno
    - layer
    - lambda
    - typescript
    HomePageUrl: https://github.com/hayd/deno-lambda
    SemanticVersion: DENO_LAMBDA_VERSION
    SourceCodeUrl: https://github.com/hayd/deno-lambda/releases/tag/DENO_LAMBDA_VERSION
