name: Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: denolib/setup-deno@v1
      with:
        deno-version: 'v0.23.0'
    - name: Test against bootstrap
      working-directory: ./tests
      run: |
        docker build -f Dockerfile -t bootstrap ..
        docker run bootstrap
