name: Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      working-directory: ./tests
      run: |
        docker build -f Dockerfile -t bootstrap ..
    - name: Run tests
      working-directory: ./tests
      run: |
        docker run bootstrap
